name: Build and Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Build Jekyll Site
      uses: helaili/jekyll-action@2.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: 'gh-pages'  # Branch to deploy to
        build_directory: '_site'  # Directory to push

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Directory containing built site
